#!/usr/bin/env perl
use LWP::UserAgent;
no warnings 'uninitialized';
use Term::ANSIColor;
$ua = LWP::UserAgent->new();
$ua->agent("Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.1) Gecko/20090624 Firefox/3.5");
system "clear";
print color('bold red');
print "\n\n					   	 	Project: Panthera\n";
print "\n						        Coder: Haroon Awan\n\n\n";
print color('bold yellow');
print "[ + ] Version: 		Open Source Edition 1.0a\n";
print "[ + ] Contact: 		mrharoonawan\@gmail\.com \n";
print "[ + ] Environment: 	Perl under Kali Linux\n";
print "[ + ] Github: 		Https://www.github.com/haroonawanethicalhacker\n";
print "[ + ] Design Scheme: 	Check DNS server allows queries for third-party names\n";
print "[ + ] Usage: 		$0 url.com\n\n";
print color('reset');
print color('bold green');
$site="$ARGV[0]";

print "[ + ] Enter url.com ... : "; 
my $url = <STDIN>;
chomp $url;
print "\n[ + ] Contacting target ...\n";
sleep (2);
print "\n[ + ] Please wait, starting Check DNS server allows queries for third-party names using Nmap ...\n";
print "\n[ + ] Collecting output, it will take a minute or more, depending on the data ...\n\n";
print "\n[ + ] Collecting host data \n";
$sysa = system("host '$url'\n\n");
print "\n[ + ] Peforming scrpit action \n";
$sys = system("nmap -sU -p 53 --script=dns-random-srcport '$url' ") ;
print "\n";
exit;
